version: '3.8'

services:
  php:
    build: src/php
    container_name: php-lb3
    volumes:
      - ./src/php:/var/www/html
    ports:
      - "8086:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db-lb3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-lb3
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
